// WARNING: Please don't edit this file. It was generated by C++/WinRT v2.0.230524.4

#pragma once
#ifndef WINRT_HL2UnityPlugin_0_H
#define WINRT_HL2UnityPlugin_0_H
WINRT_EXPORT namespace winrt::Windows::Perception::Spatial
{
    struct SpatialCoordinateSystem;
}
WINRT_EXPORT namespace winrt::HL2UnityPlugin
{
    struct IHL2ResearchMode;
    struct HL2ResearchMode;
}
namespace winrt::impl
{
    template <> struct category<winrt::HL2UnityPlugin::IHL2ResearchMode>{ using type = interface_category; };
    template <> struct category<winrt::HL2UnityPlugin::HL2ResearchMode>{ using type = class_category; };
    template <> inline constexpr auto& name_v<winrt::HL2UnityPlugin::HL2ResearchMode> = L"HL2UnityPlugin.HL2ResearchMode";
    template <> inline constexpr auto& name_v<winrt::HL2UnityPlugin::IHL2ResearchMode> = L"HL2UnityPlugin.IHL2ResearchMode";
    template <> inline constexpr guid guid_v<winrt::HL2UnityPlugin::IHL2ResearchMode>{ 0x68F5CB3B,0x79B8,0x563F,{ 0xB2,0xAC,0x51,0x19,0x1A,0x8F,0xB0,0xD0 } }; // 68F5CB3B-79B8-563F-B2AC-51191A8FB0D0
    template <> struct default_interface<winrt::HL2UnityPlugin::HL2ResearchMode>{ using type = winrt::HL2UnityPlugin::IHL2ResearchMode; };
    template <> struct abi<winrt::HL2UnityPlugin::IHL2ResearchMode>
    {
        struct WINRT_IMPL_NOVTABLE type : inspectable_abi
        {
            virtual int32_t __stdcall GetLUTEntries(uint32_t, float*, uint32_t* __resultSize, float**) noexcept = 0;
            virtual int32_t __stdcall GetCenterDepth(uint16_t*) noexcept = 0;
            virtual int32_t __stdcall GetDepthMapBuffer(uint32_t* __resultSize, uint16_t**) noexcept = 0;
            virtual int32_t __stdcall GetDepthMapTextureBuffer(int64_t*, uint32_t* __resultSize, uint8_t**) noexcept = 0;
            virtual int32_t __stdcall GetShortAbImageBuffer(uint32_t* __resultSize, uint16_t**) noexcept = 0;
            virtual int32_t __stdcall GetShortAbImageTextureBuffer(uint32_t* __resultSize, uint8_t**) noexcept = 0;
            virtual int32_t __stdcall GetLongAbImageBuffer(uint32_t* __resultSize, uint16_t**) noexcept = 0;
            virtual int32_t __stdcall GetLongAbImageTextureBuffer(uint32_t* __resultSize, uint8_t**) noexcept = 0;
            virtual int32_t __stdcall GetPointCloudBuffer(uint32_t* __resultSize, float**) noexcept = 0;
            virtual int32_t __stdcall GetLongDepthMapBuffer(uint32_t* __resultSize, uint16_t**) noexcept = 0;
            virtual int32_t __stdcall GetLongDepthMapTextureBuffer(uint32_t* __resultSize, uint8_t**) noexcept = 0;
            virtual int32_t __stdcall GetLongThrowPointCloudBuffer(uint32_t* __resultSize, float**) noexcept = 0;
            virtual int32_t __stdcall GetLFCameraBuffer(int64_t*, uint32_t* __resultSize, uint8_t**) noexcept = 0;
            virtual int32_t __stdcall GetRFCameraBuffer(int64_t*, uint32_t* __resultSize, uint8_t**) noexcept = 0;
            virtual int32_t __stdcall GetLRFCameraBuffer(int64_t*, int64_t*, uint32_t* __resultSize, uint8_t**) noexcept = 0;
            virtual int32_t __stdcall GetAccelSample(uint32_t* __resultSize, float**) noexcept = 0;
            virtual int32_t __stdcall GetGyroSample(uint32_t* __resultSize, float**) noexcept = 0;
            virtual int32_t __stdcall GetMagSample(uint32_t* __resultSize, float**) noexcept = 0;
            virtual int32_t __stdcall GetCenterPoint(uint32_t* __resultSize, float**) noexcept = 0;
            virtual int32_t __stdcall GetDepthBufferSize(int32_t*) noexcept = 0;
            virtual int32_t __stdcall GetLongDepthBufferSize(int32_t*) noexcept = 0;
            virtual int32_t __stdcall PrintDepthResolution(void**) noexcept = 0;
            virtual int32_t __stdcall PrintDepthExtrinsics(void**) noexcept = 0;
            virtual int32_t __stdcall PrintLFResolution(void**) noexcept = 0;
            virtual int32_t __stdcall PrintLFExtrinsics(void**) noexcept = 0;
            virtual int32_t __stdcall PrintRFResolution(void**) noexcept = 0;
            virtual int32_t __stdcall PrintRFExtrinsics(void**) noexcept = 0;
            virtual int32_t __stdcall DepthMapTextureUpdated(bool*) noexcept = 0;
            virtual int32_t __stdcall ShortAbImageTextureUpdated(bool*) noexcept = 0;
            virtual int32_t __stdcall LongAbImageTextureUpdated(bool*) noexcept = 0;
            virtual int32_t __stdcall PointCloudUpdated(bool*) noexcept = 0;
            virtual int32_t __stdcall LongDepthMapTextureUpdated(bool*) noexcept = 0;
            virtual int32_t __stdcall LongThrowPointCloudUpdated(bool*) noexcept = 0;
            virtual int32_t __stdcall LFImageUpdated(bool*) noexcept = 0;
            virtual int32_t __stdcall RFImageUpdated(bool*) noexcept = 0;
            virtual int32_t __stdcall AccelSampleUpdated(bool*) noexcept = 0;
            virtual int32_t __stdcall GyroSampleUpdated(bool*) noexcept = 0;
            virtual int32_t __stdcall MagSampleUpdated(bool*) noexcept = 0;
            virtual int32_t __stdcall InitializeDepthSensor() noexcept = 0;
            virtual int32_t __stdcall InitializeLongDepthSensor() noexcept = 0;
            virtual int32_t __stdcall InitializeSpatialCamerasFront() noexcept = 0;
            virtual int32_t __stdcall InitializeAccelSensor() noexcept = 0;
            virtual int32_t __stdcall InitializeGyroSensor() noexcept = 0;
            virtual int32_t __stdcall InitializeMagSensor() noexcept = 0;
            virtual int32_t __stdcall StartDepthSensorLoop() noexcept = 0;
            virtual int32_t __stdcall StartDepthSensorLoop2(bool) noexcept = 0;
            virtual int32_t __stdcall StartLongDepthSensorLoop() noexcept = 0;
            virtual int32_t __stdcall StartLongDepthSensorLoop2(bool) noexcept = 0;
            virtual int32_t __stdcall StartSpatialCamerasFrontLoop() noexcept = 0;
            virtual int32_t __stdcall StartAccelSensorLoop() noexcept = 0;
            virtual int32_t __stdcall StartGyroSensorLoop() noexcept = 0;
            virtual int32_t __stdcall StartMagSensorLoop() noexcept = 0;
            virtual int32_t __stdcall StopAllSensorDevice() noexcept = 0;
            virtual int32_t __stdcall SetReferenceCoordinateSystem(void*) noexcept = 0;
            virtual int32_t __stdcall SetPointCloudRoiInSpace(float, float, float, float, float, float) noexcept = 0;
            virtual int32_t __stdcall SetPointCloudDepthOffset(uint16_t) noexcept = 0;
        };
    };
    template <typename D>
    struct consume_HL2UnityPlugin_IHL2ResearchMode
    {
        auto GetLUTEntries(array_view<float const> uv) const;
        auto GetCenterDepth() const;
        auto GetDepthMapBuffer() const;
        auto GetDepthMapTextureBuffer(int64_t& ts) const;
        auto GetShortAbImageBuffer() const;
        auto GetShortAbImageTextureBuffer() const;
        auto GetLongAbImageBuffer() const;
        auto GetLongAbImageTextureBuffer() const;
        auto GetPointCloudBuffer() const;
        auto GetLongDepthMapBuffer() const;
        auto GetLongDepthMapTextureBuffer() const;
        auto GetLongThrowPointCloudBuffer() const;
        auto GetLFCameraBuffer(int64_t& ts) const;
        auto GetRFCameraBuffer(int64_t& ts) const;
        auto GetLRFCameraBuffer(int64_t& ts_left, int64_t& ts_right) const;
        auto GetAccelSample() const;
        auto GetGyroSample() const;
        auto GetMagSample() const;
        auto GetCenterPoint() const;
        auto GetDepthBufferSize() const;
        auto GetLongDepthBufferSize() const;
        auto PrintDepthResolution() const;
        auto PrintDepthExtrinsics() const;
        auto PrintLFResolution() const;
        auto PrintLFExtrinsics() const;
        auto PrintRFResolution() const;
        auto PrintRFExtrinsics() const;
        auto DepthMapTextureUpdated() const;
        auto ShortAbImageTextureUpdated() const;
        auto LongAbImageTextureUpdated() const;
        auto PointCloudUpdated() const;
        auto LongDepthMapTextureUpdated() const;
        auto LongThrowPointCloudUpdated() const;
        auto LFImageUpdated() const;
        auto RFImageUpdated() const;
        auto AccelSampleUpdated() const;
        auto GyroSampleUpdated() const;
        auto MagSampleUpdated() const;
        auto InitializeDepthSensor() const;
        auto InitializeLongDepthSensor() const;
        auto InitializeSpatialCamerasFront() const;
        auto InitializeAccelSensor() const;
        auto InitializeGyroSensor() const;
        auto InitializeMagSensor() const;
        auto StartDepthSensorLoop() const;
        auto StartDepthSensorLoop(bool reconstructPointCloud) const;
        auto StartLongDepthSensorLoop() const;
        auto StartLongDepthSensorLoop(bool reconstructPointCloud) const;
        auto StartSpatialCamerasFrontLoop() const;
        auto StartAccelSensorLoop() const;
        auto StartGyroSensorLoop() const;
        auto StartMagSensorLoop() const;
        auto StopAllSensorDevice() const;
        auto SetReferenceCoordinateSystem(winrt::Windows::Perception::Spatial::SpatialCoordinateSystem const& refCoord) const;
        auto SetPointCloudRoiInSpace(float centerX, float centerY, float centerZ, float boundX, float boundY, float boundZ) const;
        auto SetPointCloudDepthOffset(uint16_t offset) const;
    };
    template <> struct consume<winrt::HL2UnityPlugin::IHL2ResearchMode>
    {
        template <typename D> using type = consume_HL2UnityPlugin_IHL2ResearchMode<D>;
    };
}
#endif
