#include "pch.h"
#include "HL2ResearchMode.h"
#include "HL2ResearchMode.g.cpp"

// WARNING: This file is automatically generated by a tool. Do not directly
// add this file to your project, as any changes you make will be lost.
// This file is a stub you can use as a starting point for your implementation.
//
// To add a copy of this file to your project:
//   1. Copy this file from its original location to the location where you store 
//      your other source files (e.g. the project root). 
//   2. Add the copied file to your project. In Visual Studio, you can use 
//      Project -> Add Existing Item.
//   3. Delete this comment and the 'static_assert' (below) from the copied file.
//      Do not modify the original file.
//
// To update an existing file in your project:
//   1. Copy the relevant changes from this file and merge them into the copy 
//      you made previously.
//    
// This assertion helps prevent accidental modification of generated files.
static_assert(false, "This file is generated by a tool and will be overwritten. Open this error and view the comment for assistance.");

namespace winrt::HL2UnityPlugin::implementation
{
    com_array<float> HL2ResearchMode::GetLUTEntries(array_view<float const> uv)
    {
        throw hresult_not_implemented();
    }
    uint16_t HL2ResearchMode::GetCenterDepth()
    {
        throw hresult_not_implemented();
    }
    com_array<uint16_t> HL2ResearchMode::GetDepthMapBuffer()
    {
        throw hresult_not_implemented();
    }
    com_array<uint8_t> HL2ResearchMode::GetDepthMapTextureBuffer(int64_t& ts)
    {
        throw hresult_not_implemented();
    }
    com_array<uint16_t> HL2ResearchMode::GetShortAbImageBuffer()
    {
        throw hresult_not_implemented();
    }
    com_array<uint8_t> HL2ResearchMode::GetShortAbImageTextureBuffer()
    {
        throw hresult_not_implemented();
    }
    com_array<uint16_t> HL2ResearchMode::GetLongAbImageBuffer()
    {
        throw hresult_not_implemented();
    }
    com_array<uint8_t> HL2ResearchMode::GetLongAbImageTextureBuffer()
    {
        throw hresult_not_implemented();
    }
    com_array<float> HL2ResearchMode::GetPointCloudBuffer()
    {
        throw hresult_not_implemented();
    }
    com_array<uint16_t> HL2ResearchMode::GetLongDepthMapBuffer()
    {
        throw hresult_not_implemented();
    }
    com_array<uint8_t> HL2ResearchMode::GetLongDepthMapTextureBuffer()
    {
        throw hresult_not_implemented();
    }
    com_array<float> HL2ResearchMode::GetLongThrowPointCloudBuffer()
    {
        throw hresult_not_implemented();
    }
    com_array<uint8_t> HL2ResearchMode::GetLFCameraBuffer(int64_t& ts)
    {
        throw hresult_not_implemented();
    }
    com_array<uint8_t> HL2ResearchMode::GetRFCameraBuffer(int64_t& ts)
    {
        throw hresult_not_implemented();
    }
    com_array<uint8_t> HL2ResearchMode::GetLRFCameraBuffer(int64_t& ts_left, int64_t& ts_right)
    {
        throw hresult_not_implemented();
    }
    com_array<float> HL2ResearchMode::GetAccelSample()
    {
        throw hresult_not_implemented();
    }
    com_array<float> HL2ResearchMode::GetGyroSample()
    {
        throw hresult_not_implemented();
    }
    com_array<float> HL2ResearchMode::GetMagSample()
    {
        throw hresult_not_implemented();
    }
    com_array<float> HL2ResearchMode::GetCenterPoint()
    {
        throw hresult_not_implemented();
    }
    int32_t HL2ResearchMode::GetDepthBufferSize()
    {
        throw hresult_not_implemented();
    }
    int32_t HL2ResearchMode::GetLongDepthBufferSize()
    {
        throw hresult_not_implemented();
    }
    hstring HL2ResearchMode::PrintDepthResolution()
    {
        throw hresult_not_implemented();
    }
    hstring HL2ResearchMode::PrintDepthExtrinsics()
    {
        throw hresult_not_implemented();
    }
    hstring HL2ResearchMode::PrintLFResolution()
    {
        throw hresult_not_implemented();
    }
    hstring HL2ResearchMode::PrintLFExtrinsics()
    {
        throw hresult_not_implemented();
    }
    hstring HL2ResearchMode::PrintRFResolution()
    {
        throw hresult_not_implemented();
    }
    hstring HL2ResearchMode::PrintRFExtrinsics()
    {
        throw hresult_not_implemented();
    }
    bool HL2ResearchMode::DepthMapTextureUpdated()
    {
        throw hresult_not_implemented();
    }
    bool HL2ResearchMode::ShortAbImageTextureUpdated()
    {
        throw hresult_not_implemented();
    }
    bool HL2ResearchMode::LongAbImageTextureUpdated()
    {
        throw hresult_not_implemented();
    }
    bool HL2ResearchMode::PointCloudUpdated()
    {
        throw hresult_not_implemented();
    }
    bool HL2ResearchMode::LongDepthMapTextureUpdated()
    {
        throw hresult_not_implemented();
    }
    bool HL2ResearchMode::LongThrowPointCloudUpdated()
    {
        throw hresult_not_implemented();
    }
    bool HL2ResearchMode::LFImageUpdated()
    {
        throw hresult_not_implemented();
    }
    bool HL2ResearchMode::RFImageUpdated()
    {
        throw hresult_not_implemented();
    }
    bool HL2ResearchMode::AccelSampleUpdated()
    {
        throw hresult_not_implemented();
    }
    bool HL2ResearchMode::GyroSampleUpdated()
    {
        throw hresult_not_implemented();
    }
    bool HL2ResearchMode::MagSampleUpdated()
    {
        throw hresult_not_implemented();
    }
    void HL2ResearchMode::InitializeDepthSensor()
    {
        throw hresult_not_implemented();
    }
    void HL2ResearchMode::InitializeLongDepthSensor()
    {
        throw hresult_not_implemented();
    }
    void HL2ResearchMode::InitializeSpatialCamerasFront()
    {
        throw hresult_not_implemented();
    }
    void HL2ResearchMode::InitializeAccelSensor()
    {
        throw hresult_not_implemented();
    }
    void HL2ResearchMode::InitializeGyroSensor()
    {
        throw hresult_not_implemented();
    }
    void HL2ResearchMode::InitializeMagSensor()
    {
        throw hresult_not_implemented();
    }
    void HL2ResearchMode::StartDepthSensorLoop()
    {
        throw hresult_not_implemented();
    }
    void HL2ResearchMode::StartDepthSensorLoop(bool reconstructPointCloud)
    {
        throw hresult_not_implemented();
    }
    void HL2ResearchMode::StartLongDepthSensorLoop()
    {
        throw hresult_not_implemented();
    }
    void HL2ResearchMode::StartLongDepthSensorLoop(bool reconstructPointCloud)
    {
        throw hresult_not_implemented();
    }
    void HL2ResearchMode::StartSpatialCamerasFrontLoop()
    {
        throw hresult_not_implemented();
    }
    void HL2ResearchMode::StartAccelSensorLoop()
    {
        throw hresult_not_implemented();
    }
    void HL2ResearchMode::StartGyroSensorLoop()
    {
        throw hresult_not_implemented();
    }
    void HL2ResearchMode::StartMagSensorLoop()
    {
        throw hresult_not_implemented();
    }
    void HL2ResearchMode::StopAllSensorDevice()
    {
        throw hresult_not_implemented();
    }
    void HL2ResearchMode::SetReferenceCoordinateSystem(winrt::Windows::Perception::Spatial::SpatialCoordinateSystem const& refCoord)
    {
        throw hresult_not_implemented();
    }
    void HL2ResearchMode::SetPointCloudRoiInSpace(float centerX, float centerY, float centerZ, float boundX, float boundY, float boundZ)
    {
        throw hresult_not_implemented();
    }
    void HL2ResearchMode::SetPointCloudDepthOffset(uint16_t offset)
    {
        throw hresult_not_implemented();
    }
}
